export type RepertoireCategory = "klassik" | "film" | "tango" | "pop";
export type RepertoireStatus = "active" | "sextet" | "rehearsed" | "planned";

export interface RepertoirePiece {
  title: string;
  composer: string;
  category: RepertoireCategory;
  status: RepertoireStatus;
}

export const categoryLabels: Record<RepertoireCategory, string> = {
  klassik: "Klassik",
  film: "Filmmusik",
  tango: "Tango & Latin",
  pop: "Pop & Rock",
};

export const statusLabels: Record<RepertoireStatus, string> = {
  active: "Aktives Programm",
  sextet: "Sextett",
  rehearsed: "Angespielt",
  planned: "In Planung",
};

export const repertoire: RepertoirePiece[] = [
  // ─── ACTIVE PROGRAM ───────────────────────────────────────
  { title: "Star Wars (Main Theme)", composer: "John Williams", category: "film", status: "active" },
  { title: "El Choclo", composer: "Ángel Villoldo", category: "tango", status: "active" },
  { title: "Oblivion", composer: "Astor Piazzolla", category: "tango", status: "active" },
  { title: "Nothing Else Matters", composer: "Apocalyptica", category: "pop", status: "active" },
  { title: "Beyond Time", composer: "Apocalyptica", category: "pop", status: "active" },
  { title: "Ragtime Trios", composer: "Scott Joplin", category: "klassik", status: "active" },
  { title: "Path", composer: "Apocalyptica", category: "pop", status: "active" },
  { title: "Hallelujah", composer: "Leonard Cohen", category: "pop", status: "active" },
  { title: "Pink Panther", composer: "Henry Mancini", category: "film", status: "active" },
  { title: "Pavane", composer: "Gabriel Fauré", category: "klassik", status: "active" },
  { title: "Pavane (neue Fassung)", composer: "Gabriel Fauré", category: "klassik", status: "active" },
  { title: "Farewell", composer: "Apocalyptica", category: "pop", status: "active" },
  { title: "Lohengrin (Feierliches Stück)", composer: "Richard Wagner", category: "klassik", status: "active" },
  { title: "Bohemian Rhapsody", composer: "Queen", category: "pop", status: "active" },
  { title: "Bésame Mucho", composer: "Consuelo Velázquez", category: "tango", status: "active" },
  { title: "He's a Pirate (Fluch der Karibik)", composer: "Klaus Badelt", category: "film", status: "active" },
  { title: "Yesterday", composer: "The Beatles", category: "pop", status: "active" },
  { title: "Bittersweet", composer: "Apocalyptica", category: "pop", status: "active" },
  { title: "Let It Be", composer: "The Beatles", category: "pop", status: "active" },
  { title: "James Bond Theme", composer: "Monty Norman", category: "film", status: "active" },
  { title: "Happy", composer: "Pharrell Williams", category: "pop", status: "active" },
  { title: "Walzer Nr. 2 (Jazzsuite)", composer: "Dmitri Schostakowitsch", category: "klassik", status: "active" },
  { title: "Mission Impossible", composer: "Lalo Schifrin", category: "film", status: "active" },
  { title: "Adiós Nonino", composer: "Astor Piazzolla", category: "tango", status: "active" },
  { title: "Libertango (Quintett)", composer: "Astor Piazzolla", category: "tango", status: "active" },
  { title: "America (West Side Story)", composer: "Leonard Bernstein", category: "film", status: "active" },
  { title: "Hummelflug", composer: "Rimsky-Korsakow", category: "klassik", status: "active" },
  { title: "Locus Iste", composer: "Anton Bruckner", category: "klassik", status: "active" },
  { title: "Air", composer: "Johann Sebastian Bach", category: "klassik", status: "active" },
  { title: "Hänsel und Gretel", composer: "Engelbert Humperdinck", category: "klassik", status: "active" },
  { title: "A Portrait (Gershwin)", composer: "George Gershwin", category: "klassik", status: "active" },
  { title: "Ghostbusters", composer: "Ray Parker Jr.", category: "film", status: "active" },
  { title: "Sir Duke", composer: "Stevie Wonder", category: "pop", status: "active" },
  { title: "La Primavera (Frühling)", composer: "Antonio Vivaldi", category: "klassik", status: "active" },
  { title: "Otoño Porteño", composer: "Astor Piazzolla", category: "tango", status: "active" },
  { title: "Despacito", composer: "Luis Fonsi", category: "pop", status: "active" },
  { title: "Ave Maria", composer: "Wilhelm Fitzenhagen", category: "klassik", status: "active" },
  { title: "Der Pate (Godfather)", composer: "Nino Rota", category: "film", status: "active" },
  { title: "Cantina Band", composer: "John Williams", category: "film", status: "active" },
  { title: "Sarabande", composer: "Georg Friedrich Händel", category: "klassik", status: "active" },
  { title: "La Muerte del Ángel (Trio)", composer: "Astor Piazzolla", category: "tango", status: "active" },

  // ─── SEXTET ONLY ──────────────────────────────────────────
  { title: "Requiem", composer: "David Popper (arr. Alabaster)", category: "klassik", status: "sextet" },
  { title: "Adagio for Strings", composer: "Samuel Barber", category: "klassik", status: "sextet" },
  { title: "Abendlied", composer: "Josef Rheinberger", category: "klassik", status: "sextet" },
  { title: "Der Lindenbaum (Quintett)", composer: "Franz Schubert", category: "klassik", status: "sextet" },
  { title: "Pilgerchor (Tannhäuser, Quintett)", composer: "Richard Wagner", category: "klassik", status: "sextet" },
  { title: "Meistersinger", composer: "Richard Wagner", category: "klassik", status: "sextet" },
  { title: "Doppelkonzert", composer: "Antonio Vivaldi", category: "klassik", status: "sextet" },
  { title: "Ciaccona", composer: "Krzysztof Penderecki", category: "klassik", status: "sextet" },
  { title: "Blues Fantasy", composer: "Eduard Pütz", category: "klassik", status: "sextet" },

  // ─── REHEARSED (not in current program) ───────────────────
  { title: "Spain", composer: "Chick Corea", category: "pop", status: "rehearsed" },
  { title: "Celloquartett", composer: "Friedrich Matz", category: "klassik", status: "rehearsed" },
  { title: "Somebody That I Used to Know", composer: "Gotye", category: "pop", status: "rehearsed" },
  { title: "Phantom der Oper", composer: "Andrew Lloyd Webber", category: "film", status: "rehearsed" },
  { title: "Ba-Rock", composer: "Joschi Schumann", category: "klassik", status: "rehearsed" },
  { title: "Radioactive", composer: "Imagine Dragons", category: "pop", status: "rehearsed" },
  { title: "Game of Thrones", composer: "Ramin Djawadi", category: "film", status: "rehearsed" },
  { title: "Forrest Gump Suite", composer: "Alan Silvestri", category: "film", status: "rehearsed" },
  { title: "L'Arlésienne Suite", composer: "Georges Bizet", category: "klassik", status: "rehearsed" },
  { title: "Schlager (diverse)", composer: "diverse", category: "pop", status: "rehearsed" },
  { title: "Sherlock Holmes", composer: "Hans Zimmer", category: "film", status: "rehearsed" },
  { title: "Tetris", composer: "traditionell", category: "pop", status: "rehearsed" },
  { title: "Una Canción", composer: "unbekannt", category: "tango", status: "rehearsed" },
  { title: "Master of Puppets", composer: "Apocalyptica", category: "pop", status: "rehearsed" },
  { title: "An der schönen blauen Donau", composer: "Johann Strauss", category: "klassik", status: "rehearsed" },
  { title: "Frère Jacques Variationen", composer: "traditionell", category: "klassik", status: "rehearsed" },
  { title: "La Muerte del Ángel", composer: "Astor Piazzolla", category: "tango", status: "rehearsed" },
  { title: "Boismortier", composer: "Joseph Bodin de Boismortier", category: "klassik", status: "rehearsed" },
  { title: "Kinderlein", composer: "traditionell", category: "klassik", status: "rehearsed" },

  // ─── PLANNED (not yet played) ─────────────────────────────
  { title: "Parsifal", composer: "Richard Wagner", category: "klassik", status: "planned" },
  { title: "The Unforgiven", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Transformers", composer: "Steve Jablonsky", category: "film", status: "planned" },
  { title: "Adagio", composer: "Albinoni/Giazotto", category: "klassik", status: "planned" },
  { title: "Bolero", composer: "Maurice Ravel", category: "klassik", status: "planned" },
  { title: "Habanera (Carmen)", composer: "Georges Bizet", category: "klassik", status: "planned" },
  { title: "Libertango (Quartett)", composer: "Astor Piazzolla", category: "tango", status: "planned" },
  { title: "Celloquartett", composer: "Metzler", category: "klassik", status: "planned" },
  { title: "Romance", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Holberg Suite", composer: "Edvard Grieg", category: "klassik", status: "planned" },
  { title: "Vocalise", composer: "Sergei Rachmaninow", category: "klassik", status: "planned" },
  { title: "Akademische Festouvertüre", composer: "Johannes Brahms", category: "klassik", status: "planned" },
  { title: "Mambo", composer: "Kaiser-Lindemann", category: "tango", status: "planned" },
  { title: "Kanon", composer: "Johann Pachelbel", category: "klassik", status: "planned" },
  { title: "Popper (Original)", composer: "David Popper", category: "klassik", status: "planned" },
  { title: "Danzas", composer: "Elizondo", category: "tango", status: "planned" },
  { title: "Carmen Ouvertüre", composer: "Georges Bizet", category: "klassik", status: "planned" },
  { title: "Zortzico", composer: "Isaac Albéniz", category: "klassik", status: "planned" },
  { title: "Alborada", composer: "Elizondo", category: "tango", status: "planned" },
  { title: "Gavotten (3. Orch. Suite)", composer: "Johann Sebastian Bach", category: "klassik", status: "planned" },
  { title: "Lord of the Rings (Trailer)", composer: "Clint Mansell", category: "film", status: "planned" },
  { title: "Argentinische Tangos", composer: "Francini", category: "tango", status: "planned" },
  { title: "Autumn Morning Above the Fog", composer: "Nick Halsey", category: "klassik", status: "planned" },
  { title: "Bad Romance", composer: "Lady Gaga", category: "pop", status: "planned" },
  { title: "Coma", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Danny Boy", composer: "traditionell", category: "klassik", status: "planned" },
  { title: "Don Carlos (Ella giammai m'amò)", composer: "Giuseppe Verdi", category: "klassik", status: "planned" },
  { title: "Eine Kleine Nachtmusik", composer: "Wolfgang Amadeus Mozart", category: "klassik", status: "planned" },
  { title: "Elegiac Melody", composer: "Edvard Grieg", category: "klassik", status: "planned" },
  { title: "Enter Sandman", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Entertainer", composer: "Scott Joplin", category: "klassik", status: "planned" },
  { title: "Fade to Black", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Finlandia (Auszug)", composer: "Jean Sibelius", category: "klassik", status: "planned" },
  { title: "For Whom the Bell Tolls", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Golliwog's Cake Walk", composer: "Claude Debussy", category: "klassik", status: "planned" },
  { title: "Happy Birthday Tango", composer: "traditionell", category: "tango", status: "planned" },
  { title: "Invierno Porteño", composer: "Astor Piazzolla", category: "tango", status: "planned" },
  { title: "La Comparsa", composer: "Gerardo Rodríguez", category: "tango", status: "planned" },
  { title: "La Traviata", composer: "Giuseppe Verdi", category: "klassik", status: "planned" },
  { title: "La Última Curda", composer: "Aníbal Troilo", category: "tango", status: "planned" },
  { title: "Moon River", composer: "Henry Mancini", category: "film", status: "planned" },
  { title: "Nimrod", composer: "Edward Elgar", category: "klassik", status: "planned" },
  { title: "Nocturne", composer: "Ludwig Maurer", category: "klassik", status: "planned" },
  { title: "Notturno", composer: "Alexander Borodin", category: "klassik", status: "planned" },
  { title: "One", composer: "Apocalyptica", category: "pop", status: "planned" },
  { title: "Panis Angelicus", composer: "César Franck", category: "klassik", status: "planned" },
  { title: "Por una Cabeza", composer: "Carlos Gardel", category: "tango", status: "planned" },
  { title: "Rhapsody in Blue", composer: "George Gershwin", category: "klassik", status: "planned" },
  { title: "Simpsons", composer: "Danny Elfman", category: "film", status: "planned" },
  { title: "Still Alive", composer: "Jonathan Coulton", category: "pop", status: "planned" },
  { title: "The Final Countdown", composer: "Europe", category: "pop", status: "planned" },
  { title: "Ungarische Rhapsodie", composer: "David Popper", category: "klassik", status: "planned" },
  { title: "Wilhelm Tell Ouvertüre", composer: "Gioachino Rossini", category: "klassik", status: "planned" },
  { title: "Nussknacker", composer: "Pjotr Tschaikowsky", category: "klassik", status: "planned" },
  { title: "Peer Gynt Suite", composer: "Edvard Grieg", category: "klassik", status: "planned" },
  { title: "Hall of the Mountain King", composer: "Edvard Grieg", category: "klassik", status: "planned" },
  { title: "Fuga y Misterio", composer: "Astor Piazzolla", category: "tango", status: "planned" },
  { title: "Ricercar (Musikalisches Opfer)", composer: "Johann Sebastian Bach", category: "klassik", status: "planned" },
  { title: "Casino Royale", composer: "David Arnold", category: "film", status: "planned" },
  { title: "Fallen Leaves", composer: "Billy Talent", category: "pop", status: "planned" },
  { title: "Joga", composer: "Björk", category: "pop", status: "planned" },
  { title: "Winter", composer: "Antonio Vivaldi", category: "klassik", status: "planned" },
  { title: "Treulich geführt (Lohengrin)", composer: "Richard Wagner", category: "klassik", status: "planned" },
];
